require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/change_column_names", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ChangeColumnName. As you add validations to ChangeColumnName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChangeColumnName.create! valid_attributes
      get change_column_names_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      change_column_name = ChangeColumnName.create! valid_attributes
      get change_column_name_url(change_column_name)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_change_column_name_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      change_column_name = ChangeColumnName.create! valid_attributes
      get edit_change_column_name_url(change_column_name)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChangeColumnName" do
        expect {
          post change_column_names_url, params: { change_column_name: valid_attributes }
        }.to change(ChangeColumnName, :count).by(1)
      end

      it "redirects to the created change_column_name" do
        post change_column_names_url, params: { change_column_name: valid_attributes }
        expect(response).to redirect_to(change_column_name_url(ChangeColumnName.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChangeColumnName" do
        expect {
          post change_column_names_url, params: { change_column_name: invalid_attributes }
        }.to change(ChangeColumnName, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post change_column_names_url, params: { change_column_name: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested change_column_name" do
        change_column_name = ChangeColumnName.create! valid_attributes
        patch change_column_name_url(change_column_name), params: { change_column_name: new_attributes }
        change_column_name.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the change_column_name" do
        change_column_name = ChangeColumnName.create! valid_attributes
        patch change_column_name_url(change_column_name), params: { change_column_name: new_attributes }
        change_column_name.reload
        expect(response).to redirect_to(change_column_name_url(change_column_name))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        change_column_name = ChangeColumnName.create! valid_attributes
        patch change_column_name_url(change_column_name), params: { change_column_name: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested change_column_name" do
      change_column_name = ChangeColumnName.create! valid_attributes
      expect {
        delete change_column_name_url(change_column_name)
      }.to change(ChangeColumnName, :count).by(-1)
    end

    it "redirects to the change_column_names list" do
      change_column_name = ChangeColumnName.create! valid_attributes
      delete change_column_name_url(change_column_name)
      expect(response).to redirect_to(change_column_names_url)
    end
  end
end
