require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/details", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Detail. As you add validations to Detail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Detail.create! valid_attributes
      get details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      detail = Detail.create! valid_attributes
      get detail_url(detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      detail = Detail.create! valid_attributes
      get edit_detail_url(detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Detail" do
        expect {
          post details_url, params: { detail: valid_attributes }
        }.to change(Detail, :count).by(1)
      end

      it "redirects to the created detail" do
        post details_url, params: { detail: valid_attributes }
        expect(response).to redirect_to(detail_url(Detail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Detail" do
        expect {
          post details_url, params: { detail: invalid_attributes }
        }.to change(Detail, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post details_url, params: { detail: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested detail" do
        detail = Detail.create! valid_attributes
        patch detail_url(detail), params: { detail: new_attributes }
        detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the detail" do
        detail = Detail.create! valid_attributes
        patch detail_url(detail), params: { detail: new_attributes }
        detail.reload
        expect(response).to redirect_to(detail_url(detail))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        detail = Detail.create! valid_attributes
        patch detail_url(detail), params: { detail: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested detail" do
      detail = Detail.create! valid_attributes
      expect {
        delete detail_url(detail)
      }.to change(Detail, :count).by(-1)
    end

    it "redirects to the details list" do
      detail = Detail.create! valid_attributes
      delete detail_url(detail)
      expect(response).to redirect_to(details_url)
    end
  end
end
